name: ci

on:
  push:
    paths:
      - "**/*.lua"
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

env:
  PLUGIN_NAME: Comment

jobs:
  docs:
    runs-on: ubuntu-latest
    name: help doc check
    steps:
      - uses: actions/checkout@v4

      - name: Verify help doc
        shell: bash
        run: |
          test -s doc/${{env.PLUGIN_NAME}}.txt
